### PR TITLE
fix(internal/pool): call SetDeadline even if timeout is zero

### LINKED ISSUE #2175: `pubsub.Receive()` will timeout
#2060 cause `SetReadDeadline` not called, so `PubSub.ReceiveTimeout(ctx, 0)` will not get a read deadline set, thus it will receive the `i/o timeout` error after some time. Related #2139.

## Expected Behavior

`PubSub.ReceiveTimeout(ctx, 0)` will block forever until a message is received, So does `PubSub.Receive()`, `PubSub.ReceiveMessage()` and `PubSub.Channel()`.

## Current Behavior
`PubSub.Receive()` will timeout if read nothing for sometime.
```
received subscribe: hello <nil>
redis: 2022/08/03 22:36:54 pubsub.go:168: redis: discarding bad PubSub connection: read tcp [::1]:53016->[::1]:6379: i/o timeout
received <nil> read tcp [::1]:53016->[::1]:6379: i/o timeout
received subscribe: hello <nil>
redis: 2022/08/03 22:36:57 pubsub.go:168: redis: discarding bad PubSub connection: read tcp [::1]:53035->[::1]:6379: i/o timeout
received <nil> read tcp [::1]:53035->[::1]:6379: i/o timeout
received subscribe: hello <nil>

```

## Possible Solution
Revert #2060

## Steps to Reproduce
```go
package main

import (
    "context"
    "fmt"

    "github.com/go-redis/redis/v9"
)

func main() {
    c := redis.NewClient(&redis.Options{})
    pubsub := c.Subscribe(context.Background(), "hello")
    for {
        m, err := pubsub.Receive(context.Background())
        fmt.Println("received", m, err)
    }
}
```

## Context (Environment)
Redis: 7.0.3
go-redis: master

### PR DESCRIPTION
**Pull request by j178**
This PR revert #2060, which caused #2175.

Fixes #2175.

### CODE REVIEW

File: internal/pool/conn.go [hunk 1]
```diff
@@ -64,21 +64,17 @@ func (cn *Conn) RemoteAddr() net.Addr {
 }
 
 func (cn *Conn) WithReader(ctx context.Context, timeout time.Duration, fn func(rd *proto.Reader) error) error {
-	if timeout != 0 {
-		if err := cn.netConn.SetReadDeadline(cn.deadline(ctx, timeout)); err != nil {
-			return err
-		}
+	if err := cn.netConn.SetReadDeadline(cn.deadline(ctx, timeout)); err != nil {
```
Comment (vmihailenco) [inline internal/pool/conn.go:67]: I think this should be `timeout >= 0` so it works with PubSub

File: options.go [hunk 2]
```diff
@@ -76,7 +76,7 @@ type Options struct {
 	// Default is 3 seconds.
 	ReadTimeout time.Duration
 	// Timeout for socket writes. If reached, commands will fail
-	// with a timeout instead of blocking.
+	// with a timeout instead of blocking. Use value -1 for no timeout and 0 for default.
```
Comment (vmihailenco) [inline options.go:79]: `-1 for no timeout` is meant to disable the timeout, but it looks like you always call `SetReadDeadline` no matter what. Perhaps the comment must be updated?

Comment (vmihailenco) [inline options.go:79]: `-1 for no timeout` is meant to disable the timeout, but it looks like you always call `SetReadDeadline` no matter what. Perhaps the comment must be updated?

Comment (j178) [reply options.go:79]: This sentience is copied from the `ReadTimeout` description above.
I think `no timeout` == `disable the timeout` == `block until read/write succeeds`, do I understand this correctly?

`-1` will be adjusted to `0` here: https://github.com/go-redis/redis/blob/084c0c8914d4d84918a81b867b61d94b6c343ecd/options.go#L152-L157
then in `SetReadDeadline` or `SetWriteDeadline`, the timeout is diabled, and the read/write operation will block until it succeeds.

File: internal/pool/conn.go (hunk 1 above)
Comment (j178) [reply internal/pool/conn.go:67]: In the `pubsub.ReceiveTimeout(ctx, timeout)` case, we don't say anything about the timeout argument, is it intended to *ignore* negative timeout? 

for example `pubsub.ReceiveTimeout(ctx, -1)` means `do not set a deadline, use the previous set deadline` ?

```go
_, _ = pubsub.ReceiveTimeout(ctx, 3*time.Second) // this call set the deadline to time.Now().Add(3*time.Second)
time.Sleep(3)
_, _ = pubsub.ReceiveTimeout(ctx, -1) // this call will timeout immediately, but it may be intended to block forever
```

File: options.go (hunk 2 above)
Comment (vmihailenco) [reply options.go:79]: That is correct, but it looks like we should also support `-2` to disable `Set*Deadline` calls completely.

File: internal/pool/conn.go (hunk 1 above)
Comment (vmihailenco) [reply internal/pool/conn.go:67]: `ReceiveTimeout(0)` is the same as `Receive()` which means block forever. Negative values should probably disable `Set*Deadline` calls completely.

But I admit it is subtle.

**Comment by woutslakhorst** [comment]
I can confirm this also fixes the disconnect behaviour when using Redis sentinel.
